# Generated by Django 4.2 on 2023-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeRate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.FloatField(),
        ),
    ]
